In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,mean_absolute_error,mean_squared_error,r2_score,roc_auc_score,confusion_matrix

In [6]:
df = pd.read_csv("Food_Delivery_Time_Prediction.csv")
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,Rainy,Medium,4,Medium,Afternoon,Car,4.1,3.0,26.22,1321.10,81.54
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,Cloudy,Medium,8,Low,Night,Car,4.5,4.2,62.61,152.21,29.02
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,Snowy,Medium,9,High,Night,Bike,3.3,3.4,48.43,1644.38,64.17
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,Cloudy,Low,2,Medium,Evening,Bike,3.2,3.7,111.63,541.25,79.23
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,Rainy,High,6,Low,Night,Bike,3.5,2.8,32.38,619.81,2.34

In [7]:
df.shape

(200, 15)

In [8]:
df.isnull().sum()

Order_ID                      0
Customer_Location             0
Restaurant_Location           0
Distance                      0
Weather_Conditions            0
Traffic_Conditions            0
Delivery_Person_Experience    0
Order_Priority                0
Order_Time                    0
Vehicle_Type                  0
Restaurant_Rating             0
Customer_Rating               0
Delivery_Time                 0
Order_Cost                    0
Tip_Amount                    0
dtype: int64

In [9]:
pip install ydata_profiling

Requirement already satisfied: ydata_profiling in c:\users\yashb\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\yashb\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\yashb\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\yashb\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yashb\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\yashb\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata_profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\yashb\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yashb\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\yashb\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in c:\users\yashb\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\yashb\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata_profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\yashb\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata_profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)

In [11]:
from ydata_profiling import ProfileReport




profile = ProfileReport(df,explorative =True)
profile.to_notebook_iframe()
profile.to_file("EDA_Report.html")

C:\Users\yashb\AppData\Local\Temp\ipykernel_12364\1498196901.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 15/15 [00:00<00:00, 26.35it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [12]:
df.describe()

,Distance,Delivery_Person_Experience,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,11.498050,5.250000,3.738500,3.686500,70.494950,1046.488700,46.616650
std,6.841755,2.745027,0.703021,0.697063,29.830694,548.568922,29.361706
min,0.520000,1.000000,2.500000,2.600000,15.230000,122.300000,1.240000
25%,6.090000,3.000000,3.200000,3.100000,46.997500,553.270000,21.602500
50%,10.265000,5.000000,3.800000,3.700000,72.775000,1035.950000,47.530000
75%,16.497500,8.000000,4.300000,4.300000,96.650000,1543.125000,70.245000
max,24.900000,10.000000,5.000000,5.000000,119.670000,1997.420000,99.740000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 15 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order_ID                    200 non-null    object
 1   Customer_Location           200 non-null    object
 2   Restaurant_Location         200 non-null    object
 3   Distance                    200 non-null    float64
 4   Weather_Conditions          200 non-null    object
 5   Traffic_Conditions          200 non-null    object
 6   Delivery_Person_Experience  200 non-null    int64
 7   Order_Priority              200 non-null    object
 8   Order_Time                  200 non-null    object
 9   Vehicle_Type                200 non-null    object
 10  Restaurant_Rating           200 non-null    float64
 11  Customer_Rating             200 non-null    float64
 12  Delivery_Time               200 non-null    float64
 13  Order_Cost                  200 non-null    float64
 14  Tip_Amount                  200 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 23.6+ KB

In [14]:
df.head()

,Order_ID,Customer_Location,Restaurant_Location,Distance,Weather_Conditions,Traffic_Conditions,Delivery_Person_Experience,Order_Priority,Order_Time,Vehicle_Type,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount
0,ORD0001,"(17.030479, 79.743077)","(12.358515, 85.100083)",1.57,Rainy,Medium,4,Medium,Afternoon,Car,4.1,3.0,26.22,1321.10,81.54
1,ORD0002,"(15.398319, 86.639122)","(14.174874, 77.025606)",21.32,Cloudy,Medium,8,Low,Night,Car,4.5,4.2,62.61,152.21,29.02
2,ORD0003,"(15.687342, 83.888808)","(19.594748, 82.048482)",6.95,Snowy,Medium,9,High,Night,Bike,3.3,3.4,48.43,1644.38,64.17
3,ORD0004,"(20.415599, 78.046984)","(16.915906, 78.278698)",13.79,Cloudy,Low,2,Medium,Evening,Bike,3.2,3.7,111.63,541.25,79.23
4,ORD0005,"(14.786904, 78.706532)","(15.206038, 86.203182)",6.72,Rainy,High,6,Low,Night,Bike,3.5,2.8,32.38,619.81,2.34

In [18]:
#3 a. use onehotencoder


df = pd.get_dummies(
    df, 
    columns=['Weather_Conditions','Traffic_Conditions', 'Vehicle_Type'],
    drop_first= True
)

KeyError: "None of [Index(['Weather_Conditions', 'Traffic_Conditions', 'Vehicle_Type'], dtype='object')] are in the [columns]"

In [20]:
#3b. use feature scaling

scaler = StandardScaler()

numeric_coloumns = ["Distance","Delivery_Person_Experience","Restaurant_Rating","Customer_Rating","Delivery_Time","Order_Cost","Tip_Amount"]
df[numeric_coloumns]= scaler.fit_transform(df[numeric_coloumns])

In [21]:
df.dtypes

Order_ID                       object
Customer_Location              object
Restaurant_Location            object
Distance                      float64
Delivery_Person_Experience    float64
Order_Priority                 object
Order_Time                     object
Restaurant_Rating             float64
Customer_Rating               float64
Delivery_Time                 float64
Order_Cost                    float64
Tip_Amount                    float64
Weather_Conditions_Rainy         bool
Weather_Conditions_Snowy         bool
Weather_Conditions_Sunny         bool
Traffic_Conditions_Low           bool
Traffic_Conditions_Medium        bool
Vehicle_Type_Bike                bool
Vehicle_Type_Car                 bool
dtype: object

 STEP 2  EDA PART 
 WE NEED TOCLACULATE MEAN , MEDIAN , MODE AND VARIANCE 
 I WILL BE CALUCULATINHG MODE AND VARIANCE BECAUSE MEAN , MEDIAN AND STANDARD DEVIATION IS CALCULATED IN DESCRIBE PART

In [22]:
df.mode().iloc[0]

Order_ID                                     ORD0001
Customer_Location             (12.021992, 84.862769)
Restaurant_Location             (12.019922, 78.4686)
Distance                                    -1.49137
Delivery_Person_Experience                  1.004325
Order_Priority                                   Low
Order_Time                                 Afternoon
Restaurant_Rating                           0.087699
Customer_Rating                            -1.562593
Delivery_Time                              -0.122831
Order_Cost                                  1.401256
Tip_Amount                                 -1.515854
Weather_Conditions_Rainy                       False
Weather_Conditions_Snowy                       False
Weather_Conditions_Sunny                       False
Traffic_Conditions_Low                         False
Traffic_Conditions_Medium                      False
Vehicle_Type_Bike                              False
Vehicle_Type_Car                               False
Name: 0, dtype: object

In [23]:
df.var(numeric_only=True)

Distance                      1.005025
Delivery_Person_Experience    1.005025
Restaurant_Rating             1.005025
Customer_Rating               1.005025
Delivery_Time                 1.005025
Order_Cost                    1.005025
Tip_Amount                    1.005025
Weather_Conditions_Rainy      0.204799
Weather_Conditions_Snowy      0.183317
Weather_Conditions_Sunny      0.195754
Traffic_Conditions_Low        0.242186
Traffic_Conditions_Medium     0.225528
Vehicle_Type_Bike             0.227111
Vehicle_Type_Car              0.214975
dtype: float64

In [24]:
# viszlualition 

plt.figure(figsize=(10,6))
sns.boxplot(data=df.select_dtypes(include="number"))
plt.xticks(rotation=90)
plt.show()

C:\Users\yashb\AppData\Local\Temp\ipykernel_12364\2915689216.py:6: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

we cannot use jhavience formula because we already have distance columns .

In [27]:
df.drop(["Order_ID","Customer_Location","Restaurant_Location"],axis=1,inplace=True)

In [28]:
df.head()

,Distance,Delivery_Person_Experience,Order_Priority,Order_Time,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount,Weather_Conditions_Rainy,Weather_Conditions_Snowy,Weather_Conditions_Sunny,Traffic_Conditions_Low,Traffic_Conditions_Medium,Vehicle_Type_Bike,Vehicle_Type_Car
0,-1.454738,-0.456512,Medium,Afternoon,0.515500,-0.987317,-1.487932,0.501852,1.192403,True,False,False,False,True,False,True
1,1.439192,1.004325,Low,Night,1.085900,0.738511,-0.264987,-1.634294,-0.600810,False,False,False,False,True,False,True
2,-0.666417,1.369535,High,Night,-0.625302,-0.412041,-0.741529,1.092646,0.599332,False,True,False,False,True,True,False
3,0.335835,-1.186930,Medium,Evening,-0.767902,0.019416,1.382411,-0.923323,1.113532,False,False,False,True,False,True,False
4,-0.700119,0.273907,Low,Night,-0.340101,-1.274955,-1.280915,-0.779755,-1.511757,True,False,False,False,False,True,False

In [29]:
df["Order_Priority"] = df["Order_Priority"].map({
    "Low": 0,
    "Medium": 1,
    "High": 2
})

In [31]:
le = LabelEncoder()

df["Order_Time"] = le.fit_transform(df["Order_Time"])

In [32]:
df.head()

,Distance,Delivery_Person_Experience,Order_Priority,Order_Time,Restaurant_Rating,Customer_Rating,Delivery_Time,Order_Cost,Tip_Amount,Weather_Conditions_Rainy,Weather_Conditions_Snowy,Weather_Conditions_Sunny,Traffic_Conditions_Low,Traffic_Conditions_Medium,Vehicle_Type_Bike,Vehicle_Type_Car
0,-1.454738,-0.456512,1,0,0.515500,-0.987317,-1.487932,0.501852,1.192403,True,False,False,False,True,False,True
1,1.439192,1.004325,0,3,1.085900,0.738511,-0.264987,-1.634294,-0.600810,False,False,False,False,True,False,True
2,-0.666417,1.369535,2,3,-0.625302,-0.412041,-0.741529,1.092646,0.599332,False,True,False,False,True,True,False
3,0.335835,-1.186930,1,1,-0.767902,0.019416,1.382411,-0.923323,1.113532,False,False,False,True,False,True,False
4,-0.700119,0.273907,0,3,-0.340101,-1.274955,-1.280915,-0.779755,-1.511757,True,False,False,False,False,True,False

In [33]:
X = df.drop("Delivery_Time", axis =1)
y= df["Delivery_Time"]

Now we are creating models for tha prediction first linear regression .
train_test_split is our first step

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [36]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(160, 15)
(40, 15)
(160,)
(40,)

In [39]:
from sklearn.linear_model import LinearRegression

model= LinearRegression()

model.fit(X_train,y_train)

LinearRegression()

In [40]:
y_pred = model.predict(X_test)

In [41]:
# evlauation step 

mae = mean_absolute_error(y_test,y_pred)
mse = mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)

In [42]:
print("Mean Error", mae)
print("Mean squared error", mse)
print("R2_score", r2)

Mean Error 0.9073311088130577
Mean squared error 1.1442278858148152
R2_score -0.09539733469488931

2 model = logistic regression 
we will use another model for prediction for seeing which make more accurate predictions

In [48]:
df["Delivery_Status"]= (df["Delivery_Time"]<= df["Delivery_Time"].median()).astype(int)

In [49]:
X = df.drop(["Delivery_Time","Delivery_Status"], axis = 1)
y = df["Delivery_Status"]

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2,random_state=42)

In [51]:
log_model = LogisticRegression()

log_model.fit(X_train,y_train)

LogisticRegression()

In [52]:
y_pred = log_model.predict(X_test)

In [55]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        19

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

In [56]:
print(confusion_matrix(y_test,y_pred))

[[21  0]
 [ 0 19]]

In [58]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [59]:
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

In [60]:
print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

print("\nConfusion Matrix")
print(cm)

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 1.0
Precision: 1.0
Recall   : 1.0
F1 Score : 1.0

Confusion Matrix
[[21  0]
 [ 0 19]]

Classification Report
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        21
           1       1.00      1.00      1.00        19

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40

camparing the models

In [61]:
print("Linear Regression performmace ")
print("Mae", mae)
print("Mse", mse)
print("R2 score",r2_score)

Linear Regression performmace
Mae 0.9073311088130577
Mse 1.1442278858148152
R2 score <function r2_score at 0x00000199E63E8180>

In [62]:
print("Logostic Regression performnance ")

print("Accuracy", accuracy)
print("Precision", precision)
print("Recall", recall)
print("F1_score",f1)

Logostic Regression performnance
Accuracy 1.0
Precision 1.0
Recall 1.0
F1_score 1.0

In [ ]:

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

C:\Users\yashb\AppData\Local\Temp\ipykernel_12364\1781682877.py:9: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [64]:
from sklearn.metrics import roc_curve, roc_auc_score

y_prob = log_model.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)

auc = roc_auc_score(y_test, y_prob)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {auc:.2f}")
plt.plot([0,1],[0,1],'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

C:\Users\yashb\AppData\Local\Temp\ipykernel_12364\1597553964.py:16: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

1. Optimize Delivery Routes
Deliveries covering longer distances generally require more time.
Route optimization can reduce travel time and fuel costs.
2. Improve Staffing During Rush Hours
Delivery times increase during heavy traffic periods.
Scheduling more delivery personnel during peak hours can reduce delays.
3. Train Delivery Personnel
More experienced delivery personnel may complete deliveries more efficiently.
Regular training can improve delivery speed and customer satisfaction.
4. Improve Order Assignment
Assign nearby delivery personnel to nearby orders.
This can reduce average delivery time.
5. Monitor Weather Conditions
Rain and poor weather often increase delivery times.
Customers can be notified about expected delays during adverse weather.

final conculusion

This project developed both a Linear Regression model for predicting delivery time and a Logistic Regression model for classifying deliveries as Fast or Delayed.After preprocessing, feature engineering, and model training, both models were evaluated using appropriate metrics. The analysis indicates that factors such as distance, traffic conditions, weather, and delivery personnel experience significantly influence delivery performance. These findings can help delivery companies optimize operations, reduce delays, and improve customer satisfaction.