In [28]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
df = pd.read_csv("DataCoSupplyChainDataset.csv", encoding="latin-1")
df.shape

(180519, 53)

In [30]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [31]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [32]:
df.duplicated().sum()

np.int64(0)

In [33]:
df.describe()

,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Late_delivery_risk,Category Id,Customer Id,Customer Zipcode,Department Id,Latitude,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Price,Product Status
count,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180519.000000,180516.000000,180519.000000,180519.000000,...,180519.000000,180519.000000,180519.000000,180519.000000,24840.000000,180519.000000,180519.000000,0.0,180519.000000,180519.0
mean,3.497654,2.931847,21.974989,183.107609,0.548291,31.851451,6691.379495,35921.126914,5.443460,29.719955,...,2.127638,203.772096,183.107609,21.974989,55426.132327,692.509764,31.851451,NaN,141.232550,0.0
std,1.623722,1.374449,104.433526,120.043670,0.497664,15.640064,4162.918106,37542.461122,1.629246,9.813646,...,1.453451,132.273077,120.043670,104.433526,31919.279101,336.446807,15.640064,NaN,139.732492,0.0
min,0.000000,0.000000,-4274.979980,7.490000,0.000000,2.000000,1.000000,603.000000,2.000000,-33.937553,...,1.000000,9.990000,7.490000,-4274.979980,1040.000000,19.000000,2.000000,NaN,9.990000,0.0
25%,2.000000,2.000000,7.000000,104.379997,0.000000,18.000000,3258.500000,725.000000,4.000000,18.265432,...,1.000000,119.980003,104.379997,7.000000,23464.000000,403.000000,18.000000,NaN,50.000000,0.0
50%,3.000000,4.000000,31.520000,163.990005,1.000000,29.000000,6457.000000,19380.000000,5.000000,33.144863,...,1.000000,199.919998,163.990005,31.520000,59405.000000,627.000000,29.000000,NaN,59.990002,0.0
75%,5.000000,4.000000,64.800003,247.399994,1.000000,45.000000,9779.000000,78207.000000,7.000000,39.279617,...,3.000000,299.950012,247.399994,64.800003,90008.000000,1004.000000,45.000000,NaN,199.990005,0.0
max,6.000000,4.000000,911.799988,1939.989990,1.000000,76.000000,20757.000000,99205.000000,12.000000,48.781933,...,5.000000,1999.989990,1939.989990,911.799988,99301.000000,1363.000000,76.000000,NaN,1999.989990,0.0

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [35]:
pip install ydata_profiling

Requirement already satisfied: ydata_profiling in c:\users\yashb\anaconda3\lib\site-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.3.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.12.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in c:\users\yashb\anaconda3\lib\site-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.3.5)
Requirement already satisfied: minify-html>=0.15.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (2.32.5)
Requirement already satisfied: tqdm<5,>=4.66.3 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.14.5)
Requirement already satisfied: typeguard<5,>=4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.6.0)
Requirement already satisfied: imagehash==4.3.2 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in c:\users\yashb\anaconda3\lib\site-packages (from ydata_profiling) (0.62.1)
Requirement already satisfied: PyWavelets in c:\users\yashb\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (1.9.0)
Requirement already satisfied: pillow in c:\users\yashb\anaconda3\lib\site-packages (from imagehash==4.3.2->ydata_profiling) (12.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yashb\anaconda3\lib\site-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\yashb\anaconda3\lib\site-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\yashb\anaconda3\lib\site-packages (from numba<0.63,>=0.60->ydata_profiling) (0.45.1)
Requirement already satisfied: pytz>=2020.1 in c:\users\yashb\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\yashb\anaconda3\lib\site-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: joblib>=0.14.1 in c:\users\yashb\anaconda3\lib\site-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.5.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\yashb\anaconda3\lib\site-packages (from pydantic<3,>=2->ydata_profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yashb\anaconda3\lib\site-packages (from requests<3,>=2.32.0->ydata_profiling) (2026.6.17)
Requirement already satisfied: patsy>=0.5.6 in c:\users\yashb\anaconda3\lib\site-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.1)
Requirement already satisfied: colorama in c:\users\yashb\anaconda3\lib\site-packages (from tqdm<5,>=4.66.3->ydata_profiling) (0.4.6)
Requirement already satisfied: attrs>=19.3.0 in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.5)
Requirement already satisfied: puremagic in c:\users\yashb\anaconda3\lib\site-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\yashb\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata_profiling) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (c:\Users\yashb\anaconda3\Lib\site-packages)

In [36]:
from ydata_profiling import ProfileReport

In [37]:
profile = ProfileReport(df,explorative=True)
profile.to_file("EDA_01.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 53/53 [02:59<00:00,  3.38s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [38]:
df.drop(["Customer Email", "Customer Password", "Product Status", "Product Description", "Order Zipcode",
        "Delivery Status", "Late_delivery_risk", "shipping date (DateOrders)",
        "Customer Fname", "Customer Lname", "Customer Street", "Customer Zipcode", "Product Image",
        "Order Item Id", "Order Id", "Customer Id", "Order Customer Id", "Product Category Id", "Category Id",
        "Order Item Cardprod Id", "Product Card Id", "Order Item Total", "Order Profit Per Order", "Order Item Product Price" ],axis=1,inplace=True)

In [39]:
df.drop(["Customer City", "Order City", "Customer State", "Order State", "Order Country", "Customer Country"], axis=1,inplace=True)

In [40]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Category Name,Customer Segment,Department Id,Department Name,Latitude,...,Order Item Discount,Order Item Discount Rate,Order Item Profit Ratio,Order Item Quantity,Sales,Order Region,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Sporting Goods,Consumer,2,Fitness,18.251453,...,13.110000,0.04,0.29,1,327.75,Southeast Asia,COMPLETE,Smart watch,327.75,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Sporting Goods,Consumer,2,Fitness,18.279451,...,16.389999,0.05,-0.80,1,327.75,South Asia,PENDING,Smart watch,327.75,Standard Class
2,CASH,4,4,-247.779999,309.720001,Sporting Goods,Consumer,2,Fitness,37.292233,...,18.030001,0.06,-0.80,1,327.75,South Asia,CLOSED,Smart watch,327.75,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Sporting Goods,Home Office,2,Fitness,34.125946,...,22.940001,0.07,0.08,1,327.75,Oceania,COMPLETE,Smart watch,327.75,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Sporting Goods,Corporate,2,Fitness,18.253769,...,29.500000,0.09,0.45,1,327.75,Oceania,PENDING_PAYMENT,Smart watch,327.75,Standard Class

In [41]:
df.duplicated().sum()

np.int64(0)

In [42]:
df.isnull().sum()

Type                             0
Days for shipping (real)         0
Days for shipment (scheduled)    0
Benefit per order                0
Sales per customer               0
Category Name                    0
Customer Segment                 0
Department Id                    0
Department Name                  0
Latitude                         0
Longitude                        0
Market                           0
order date (DateOrders)          0
Order Item Discount              0
Order Item Discount Rate         0
Order Item Profit Ratio          0
Order Item Quantity              0
Sales                            0
Order Region                     0
Order Status                     0
Product Name                     0
Product Price                    0
Shipping Mode                    0
dtype: int64

In [43]:
df['delay_days'] = df['Days for shipping (real)'] - df['Days for shipment (scheduled)']

In [44]:
df['delay_days'].head()

0   -1
1    1
2    0
3   -1
4   -2
Name: delay_days, dtype: int64

In [46]:
df['delay_days'].shape

(180519,)