In [42]:
import numpy as  np 
import pandas as pd 

from sklearn.model_selection import  train_test_split

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error ,r2_score
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
data = pd.read_csv('advertising.csv')
data.head(5)

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [44]:
data.shape

(200, 4)

In [45]:
data.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [46]:
X = data[['TV', 'Radio', 'Newspaper']]
y= data['Sales']  # target variable 

X.head(5)

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [47]:
y.head(5)

0    22.1
1    10.4
2    12.0
3    16.5
4    17.9
Name: Sales, dtype: float64

In [48]:
X.corr()

                 TV     Radio  Newspaper
TV         1.000000  0.054809   0.056648
Radio      0.054809  1.000000   0.354104
Newspaper  0.056648  0.354104   1.000000

In [49]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# calcualte vif for each other 
vif_data = pd.DataFrame()

vif_data["feature"] =  X.columns

vif_data["VIF"] = [variance_inflation_factor(X.values,i) for i in range(X.shape[1])]

print("Variance Inflation Factor :")
print(vif_data)

Variance Inflation Factor :
     feature       VIF
0         TV  2.486772
1      Radio  3.285462
2  Newspaper  3.055245

In [50]:
X_train, X_test, y_train , y_test = train_test_split(X,y, test_size=0.3, random_state = 42)
X_train.head(5)

        TV  Radio  Newspaper
169  284.3   10.6        6.4
97   184.9   21.0       22.0
31   112.9   17.4       38.6
12    23.8   35.1       65.9
35   290.7    4.1        8.5

In [51]:
y_train.shape

(140,)

In [52]:
linear_model = LinearRegression()
linear_model.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_test_pred = linear_model.predict(X_train)
y_test_pred

array([21.11848606, 16.98365454, 12.88719008, 10.146882  , 20.81051619,
        7.60357179, 23.33666094,  7.17422814, 12.51775562, 10.19496565,
       11.13861029,  9.11455109, 16.90191934, 17.96632665, 15.89793301,
       18.17658466, 15.510838  , 19.17462667, 17.4985278 , 21.78302526,
       10.9293974 , 14.24097657, 10.85062985, 18.0766062 ,  9.94653599,
       17.50801696, 13.40425105, 23.58480318, 11.12777184, 23.56593295,
        7.47758575, 19.35934987, 25.15601575, 21.03343797, 18.74594783,
       16.46994473, 13.96563758, 11.38029263, 19.5072497 , 15.43483321,
       16.00504458, 10.34459768, 20.27054803, 12.52878796, 21.23675469,
       11.72760084,  9.07362481, 19.37602996, 15.76001999, 18.4291764 ,
        9.73610277, 21.5057118 , 24.78028021, 18.29999208, 18.86305778,
       14.99254145, 16.39431899,  9.071848  , 17.34382113, 21.0416217 ,
       18.13647832,  5.68991196,  6.20008935, 14.64403843, 19.34637486,
       18.921619  , 20.77018074, 23.16054093, 18.30811117, 21.08784684,
       19.16751459, 22.00876047, 12.02354208, 17.05018658, 16.90339981,
        9.8707849 , 17.56824551, 17.36720965, 19.7397033 , 20.32095599,
       13.4686262 , 19.99596368, 20.51698434,  9.82240471, 11.75708961,
       10.07468828, 13.29018739, 18.13442792,  6.69220846, 13.26205172,
       21.31795487, 17.22484   , 15.94487623,  5.42824533, 10.80634355,
       19.13851812, 16.08163892, 19.59439898, 24.3333995 ,  9.72234815,
       24.93637998, 11.20598805, 16.51385761, 25.14175908, 13.35407164,
       21.90558434,  9.80301112, 16.04361391, 10.35933109, 21.43354239,
       18.93767452, 12.67685513, 18.17592073, 14.14618209, 16.09031065,
        6.33723064,  9.5119888 , 14.18303349, 13.09761099, 18.02459867,
       11.52255765, 20.93732576,  9.95240817,  8.9174723 , 12.47700742,
       16.72161506, 16.63589353, 13.87507001, 15.347211  , 18.81008476,
        8.37972701, 18.13398567, 19.71606541, 21.52710366, 12.34794565,
        7.44882896, 19.42512797, 20.31866992, 14.78471901, 20.96639405])

In [57]:
y_test.head

<bound method NDFrame.head of 95     16.9
15     22.4
30     21.4
158     7.3
128    24.7
115    12.6
69     22.3
170     8.4
174    16.5
45     16.1
66     11.0
182     8.7
165    16.9
78      5.3
186    10.3
177    16.7
56      5.5
152    16.6
82     11.3
68     18.9
124    19.7
16     12.5
148    10.9
93     22.2
65     11.3
60      8.1
84     21.7
67     13.4
125    10.6
132     5.7
9      15.6
18     11.3
55     23.7
75      8.7
150    16.1
104    20.7
135    11.6
137    20.8
164    11.9
76      6.9
79     11.0
197    14.8
38     10.1
24      9.7
122    16.6
195     7.6
29     10.5
19     14.6
143    10.4
86     12.0
114    14.6
173    16.7
5       7.2
126     6.6
117     9.4
73     11.0
140    10.9
98     25.4
172     7.6
96     16.7
Name: Sales, dtype: float64>

In [55]:
test_results = pd.DataFrame({
    'Original sales Test ': y_test ,
    'Predicted sales Test ': y_test_pred
})

##display the first few test result 
print("Testing Data result :")
print(test_results.head())

ValueError: array length 140 does not match index length 60

In [56]:
mse_test = mean_squared_error(y_test,y_test_pred)
r2_test = r2_score(y_test,y_test_pred)

print(f'Multiple Linear Regression - Testing MSE:{mse_test}, Testing R2: {r2_test}')

ValueError: Found input variables with inconsistent numbers of samples: [60, 140]